#+TITLE: datamuse

A Common Lisp library wrapping version 1.1 of the [[https://www.datamuse.com/api/][Datamuse API]].

From the Datamuse site:

#+BEGIN_QUOTE
The Datamuse API is a word-finding query engine for developers. You can use it in your apps to find words that match a given set of constraints and that are likely in a given context. You can specify a wide variety of constraints on meaning, spelling, sound, and vocabulary in your queries, in any combination.

The API gives you programmatic access to most of the functionality of Datamuse's websites, including OneLook, RhymeZone, Rimar.io, and WikSearch.
#+END_QUOTE

Datamuse very generously allows up to 100,000 queries per day without an API key. Thus no setup is needed for this library--just ~quickload~ it and go! :)

* Exported symbols

- function ~words~ - Get a list of words matching a query.

- function ~words*~ - Get a list of words and their metadata matching a query.

- function ~suggestions~ - Get a list of suggestions to a query string.

- function ~suggestions*~ - Get a list of suggestions to a query string and their metadata.

- function ~parameter-documentation~ - Get the documentation string for the specified parameter to ~words~ / ~words*~.

- symbol ~+words-query-parameters+~ - Alist mapping ~words~ and ~words*~ parameter names to the equivalent parameter name in Datamuse's API.

Please see the docstrings for each symbol, the ~parameter-documentation~ function, and the [[http://www.datamuse.com/api/][Datamuse API documentation]] for more information.

* Similar libraries

- [[https://github.com/phoe/wordnet][wordnet]] - Lisp interface to the lexicographic database [[https://wordnet.princeton.edu/][WordNet]].
